.catalog:
  name: "Kubernetes"
  version: "v0.1.0-rancher1"
  description: "Rancher Kubernetes service"
  questions:
      - variable: "api_server_port"
        label: "Kubernetes API port"
        type: "string"
        required: true
        default: "8090"
        description: This is the port that the Kubernetes API server should listen on.

kubernetes:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
    retain_ip: true

etcd:
    health_check:
        request_line: GET /health HTTP/1.0
        port: 2379
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2
    retain_ip: true
    scale: 3

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

scheduler:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10251
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

controller-manager:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10252
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

kubectld:
    health_check:
        port: 8091
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2


rancher-ingress-controller:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

