.catalog:
  name: Kubernetes
  version: v1.5.2-rancher1-2
  description: Rancher Kubernetes service
  minimum_rancher_version: v1.4.0-rc1
  maximum_rancher_version: v1.4.0-rc1
  questions:
  - variable: EMBEDDED_BACKUPS
    label: Enable Backups
    description: "Periodically backup state to /var/etcd/backups. Mount network storage here on all hosts before continuing"
    required: true
    default: true
    type: boolean
  - variable: BACKUP_PERIOD
    label: Backup Creation Period
    description: Create a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 15m0s
    type: string
  - variable: BACKUP_RETENTION
    label: Backup Retention Period
    description: Expire a backup after this amount of time passes. Must conform to duration format
    required: true
    default: 24h
    type: string
  - variable: CLOUD_PROVIDER
    label: Cloud Provider
    description: The cloud provider on which Kubernetes is running
    required: true
    default: rancher
    type: enum
    options:
     - rancher
     - aws
  - variable: DISABLE_ADDONS
    label: Disable rancher addons
    description: Warning, Setting this to true will disable SkyDNS, dashboard, helm and other k8s services. This is meant for advanced users who want to implement their own DNS, UI and other addons.
    required: true
    default: false
    type: enum
    options:
     - true
     - false
  - variable: POD_INFRA_CONTAINER_IMAGE
    label: Pod Infra Container Image
    description: The image whose network/ipc namespaces containers in each pod will use. (It uses kubelet default if left empty)
    required: false
    default: "gcr.io/google_containers/pause-amd64:3.0"
    type: string

kubernetes:
    metadata:
        sans:
        - "IP:10.43.0.1"
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 80
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
    retain_ip: true

etcd:
    retain_ip: true
    scale_policy:
        increment: 1
        max: 3
        min: 1
    health_check:
        port: 2378
        request_line: GET /health HTTP/1.0
        interval: 5000
        response_timeout: 3000
        unhealthy_threshold: 3
        healthy_threshold: 2
        recreate_on_quorum_strategy_config:
            quorum: 2
        strategy: recreateOnQuorum

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

scheduler:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10251
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

controller-manager:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10252
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

kubectld:
    health_check:
        port: 8091
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2


rancher-ingress-controller:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10241
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
