name: Portworx
description: |
  Volume plugin for Portworx Elastic Data Fabric, providing scale-out persistent storage for containers.
version: "2.0.3.1-oci"
category: Storage
labels:
  io.rancher.orchestration.supported: 'cattle'
