version: '2'
services:
  ipsec:
    # IMPORTANT!!!! DO NOT CHANGE VERSION ON UPGRADE
    image: rancher/net:holder
    command: sh -c "echo Refer to router sidekick for logs; mkfifo f; exec cat f"
    network_mode: ipsec
    ports:
    - 500:500/udp
    - 4500:4500/udp
    labels:
      io.rancher.sidekicks: router,cni-driver
      io.rancher.scheduler.global: 'true'
  router:
    cap_add:
    - NET_ADMIN
    image: rancher/net:v0.8.1
    network_mode: container:ipsec
    environment:
      RANCHER_DEBUG: '${RANCHER_DEBUG}'
    labels:
      io.rancher.container.create_agent: 'true'
      io.rancher.container.agent_service.ipsec: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
  cni-driver:
    privileged: true
    image: rancher/net:v0.8.1
    command: sh -c "touch /var/log/rancher-ipam.log && exec tail ---disable-inotify -F /var/log/rancher-ipam.log"
    network_mode: host
    pid: host
    labels:
      io.rancher.network.cni.binary: 'rancher-bridge'
      io.rancher.container.dns: 'true'
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
