name: Rancher EBS
description: |
  Docker volume plugin for Amazon EBS
version: 0.2.1
category: Storage
labels:
  io.rancher.certified: Experimental
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
