name: Rancher EBS
description: |
  Docker volume plugin for Amazon EBS
version: 0.2.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
