name: Rancher VXLAN
description: |
  Rancher Networking plugin using VXLAN overlay.
version: v0.0.3
category: Networking
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos'
