version: '2'
services:
  secrets-driver:
    privileged: true
    image: rancher/storage-secrets:v0.9.6
    network_mode: host
    environment:
        RANCHER_DEBUG: true
    volumes:
    - /var/run:/var/run
    - /dev:/host/dev
    - /var/lib/rancher/volumes:/var/lib/rancher/volumes:shared
    logging:
      driver: json-file
      options:
        max-file: '2'
        max-size: 25m
    labels:
      io.rancher.container.agent.role: environment,agent
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'
