version: '2'
services:
  scheduler:
    image: rancher/scheduler:v0.5.1
    command: scheduler
    labels:
        io.rancher.container.create_agent: "true"
        io.rancher.container.agent_service.scheduling: "true"
    logging:
      driver: json-file
      options:
        max-size: 25m
        max-file: '2'
