name: Rancher EFS
description: |
  Docker volume and Flex Vol plugin for Amazon EFS
version: 0.2.0
category: Storage
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle,mesos,swarm'
